// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAzw_HSvR2P0hrKb_8lI11vEJJBf_p0k0',
    appId: '1:367616506810:android:d88ec0d52233e512077b83',
    messagingSenderId: '367616506810',
    projectId: 'manage-65052',
    storageBucket: 'manage-65052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHDA5n6Dr-QPeiUI4rhpKBBlhN7gInNY',
    appId: '1:367616506810:ios:5d172868bf5c3391077b83',
    messagingSenderId: '367616506810',
    projectId: 'manage-65052',
    storageBucket: 'manage-65052.firebasestorage.app',
    iosBundleId: 'com.mycompany.salarymanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbL5Xe8PVV5VRAXmarbnCNCHiA2vHta9M',
    appId: '1:367616506810:web:8af0bab5c039cb8e077b83',
    messagingSenderId: '367616506810',
    projectId: 'manage-65052',
    authDomain: 'manage-65052.firebaseapp.com',
    storageBucket: 'manage-65052.firebasestorage.app',
    measurementId: 'G-YFT9CY1TJ0',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbL5Xe8PVV5VRAXmarbnCNCHiA2vHta9M',
    appId: '1:367616506810:web:8af0bab5c039cb8e077b83',
    messagingSenderId: '367616506810',
    projectId: 'manage-65052',
    authDomain: 'manage-65052.firebaseapp.com',
    storageBucket: 'manage-65052.firebasestorage.app',
    measurementId: 'G-YFT9CY1TJ0',
  );

}